params:
    interpolation_delay: .2
    use_smoothing_interpolator: true
    blending_duration: 2.
    backend_timeout: .5
ros_topics:
    joint_state: /robot/joint_state
    rmpflow_commands: 
        command: /cortex/arm/command
        ack: /cortex/arm/command/ack
        suppress: /cortex/arm/command/suppress
        interpolated: /cortex/arm/command/interpolated
